name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'reports-test'
          mysql user: 'prisma'
          mysql password: 'senhatemp'

      - name: Install dependencies
        run: yarn install

      - name: Migrate database
        run: yarn migrate:dev

      - name: Run tests
        run: yarn test:cov
