name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'reports-test'
          mysql user: 'prisma'
          mysql password: 'senhatemp'

      - name: Install dependencies
        run: yarn install

      - name: Migrate database
        run: yarn migrate:dev

      - name: Create coverage folder
        run: mkdir coverage

      - name: Run tests
        run: yarn jest --coverage

      # - name: Monitor coverage
      #   uses: slavcodev/coverage-monitor-action@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     coverage_path: "coverage/clover.xml"
      #     threshold_alert: 10
      #     threshold_warning: 50
      #     threshold_metric: "lines"
