export enum AuditEventEnum {
  ClientCreated = 1,
  ClientUpdated = 2,
  PurchaseCreated = 3,
  PurchaseUpdated = 4,
  ItemCreated = 5,
  ItemUpdated = 6,
  ProductCreated = 7,
  ProductUpdated = 8,
  SellerCreated = 9,
  SellerUpdated = 10,
  SupervisorCreated = 11,
  SupervisorUpdated = 12,
  StoreCreated = 13,
  StoreUpdated = 14,
  ViewPurchase = 15,
  ViewItem = 16,
  ViewSeller = 17,
  CreateAdCampaignViaAdGroup = 18,
  CreateAdCampaign = 19,
  UpdateAdCampaign = 20,
  CreateAdGroupViaAd = 21,
  CreateAdGroup = 22,
  UpdateAdGroup = 23,
  CreateAdCampaignViaAd = 24,
  CreateAd = 25,
  UpdateAd = 26,
}
